---
- name: ensure apache2 is installed
  apt: pkg=apache2 state=latest
  notify:
  - restart apache2
- name: ensure php5 is installed
  apt: pkg=php5 state=latest
  notify:
  - restart apache2
- name: ensure libapache2-mod-php5 is installed
  apt: pkg=libapache2-mod-php5 state=latest
  notify:
  - restart apache2
- name: ensure mod_php5 is enabled
  apache2_module: name=php5 state=present
- name: ensure apache2 is enabled
  service: name=apache2 state=started enabled=yes

